version: "3"
services:
  node:
    image: rybakou/node
    build: .
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=4000
      - POSTGRES_HOST=${POSTGRES_NAME}
    volumes:
      - .:/usr/app
      - ./logs:/usr/app/logs
      - node_modules:/usr/app/node_modules
    networks:
      - app-network
  postgres:
    image: rybakou/postgres
    build: ./database
    container_name: ${POSTGRES_NAME}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
  logs:
